version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
