services:
  resistance:
    image: resistance
    container_name: resistance_c
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 2
    build:
      dockerfile: Dockerfile
      context: .
    restart: no
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - resistance_network

  postgres:
    image: postgres
    container_name: postgres_c
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5400:5432
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -d postgres -h localhost -p 5432 -U username'" ]
      interval: 2s
      timeout: 5s
      retries: 2
    networks:
      - resistance_network

networks:
  resistance_network:
    name: resistance_network
    driver: bridge