version: '3.9'

services:
  app:
    image: resistance-social-network:alpine3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 2
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:10-beta1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: [ "postgres", "-c", "wal_level=logical" ]